version: "3.2"
services:
  gas_consumption_supply_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: "php artisan serve --host=0.0.0.0"
    volumes:
      - .:/app
    ports:
      - 1047:8000
    networks:
      - gas_consumption_supply_network

  gas_consumption_supply_queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: "php artisan queue:work"
    networks:
      - gas_consumption_supply_network

  gas_consumption_supply_database:
    image: mariadb:10.5.8
    environment:
      - MYSQL_ROOT_PASSWORD=Ubuxa##99
      - MYSQL_DATABASE=forge
      - MYSQL_USER=forge
      - MYSQL_PASSWORD=Ubuxa##99
    networks:
      - gas_consumption_supply_network
  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 1048:80
    environment:
      - PMA_HOST=gas_consumption_supply_database
      - PMA_PASSWORD=Ubuxa##99
    networks:
      - gas_consumption_supply_network
    restart: unless-stopped
    volumes:
      - .:/app

networks:
  gas_consumption_supply_network:
