version: "3.2"
services:
  gas_consumption_supply_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: "php artisan serve --host=0.0.0.0"
    volumes:
      - .:/app
    ports:
      - 1010:8000
    networks:
      - gas_consumption_supply_network

  gas_consumption_supply_queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: "php artisan queue:work"
    networks:
      - gas_consumption_supply_network

  mysql:
    image: mariadb:10.5.8
    environment:
      - MYSQL_ROOT_PASSWORD=forge
      - MYSQL_DATABASE=gas_consumption_supply
      - MYSQL_USER=forge
      - MYSQL_PASSWORD=forge
    networks:
      - gas_consumption_supply_network
  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "1012:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PASSWORD=forge
    networks:
      - gas_consumption_supply_network
    restart: unless-stopped
    volumes:
      - ./:/app

networks:
  gas_consumption_supply_network:
